CC = gcc
CFLAGS = -Wall -Werror -g -O2
LIBS = -lm

all: tinyFsDemo

libDisk.o: libDisk.c libDisk.h
	$(CC) $(CFLAGS) -c -o $@ $<

libTinyFS.o: libTinyFS.c libTinyFS.h
	$(CC) $(CFLAGS) -c -o $@ $<

tinyFsDemo.o: tinyFsDemo.c libTinyFS.h
	$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f *.o tinyFsDemo